name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # change this if your main branch is different

permissions:
  contents: write  # needed to push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libssl-dev zlib1g-dev libbz2-dev \
            libreadline-dev libsqlite3-dev wget curl llvm \
            libncursesw5-dev xz-utils tk-dev libxml2-dev \
            libxmlsec1-dev libffi-dev liblzma-dev

      - name: Run make all
        run: make all

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ 

      - name: Force add build artifacts
        run: |
          git checkout gh-pages
          git config --global user.email "thomas.s2000@hotmail.com"
          git config --global user.name "GitHub Actions"
          git add -f build/
          git commit -m "Add build artifacts" || echo "No changes to commit"
